### PR TITLE
+ Upgraded to v3 api version.

### PR DESCRIPTION
**Pull request by suvansh-rana**
+ Added icons to template, also added some styles to them.
+ Formated the code according to PEP* design guidelines.

### CODE REVIEW

**Comment by JulianNorton** [comment]
@suvansh-rana thanks so much for this! My only feedback is that the images are increasing the load time too much. The load time on an empty cache has to be under 100ms. Please add lazy loading, or remove the images. 
image

**Comment by suvansh-rana** [comment]
The map gif was not lazily loading previously because the `src` attribute was provided to it, now I have fixed that issue and it will surely add up to the load speed.

I tried making the icons lazy but the `DOMContentLoaded` time was exceeding `100ms`  so I removed the images but after that too, the `DOMContentLoaded` time was exceeding `100ms`.

So I tried applying response minification and it helped! 

check it out #12

Screenshot (4)

**Comment by JulianNorton** [comment]
@suvansh-rana - Perfect! 💯 Very much appreciate you putting this together. Merging into production now!

**Comment by suvansh-rana** [comment]
Really enjoyed working on your project 🎉

**Pull request merged**
